import type { LucideIcon } from "lucide-react";
import {
  Code2,
  FileCode,
  Boxes,
  Package,
  Gauge,
  GitBranch,
  Binary,
  Database,
  Network,
  KeyRound,
  Layers,
  Terminal,
  FlaskConical,
  FileCheck,
  Bug,
  Workflow,
  BarChart3,
  FileText,
  Cloud,
  Container,
  LineChart,
  Box,
  Palette,
  Type,
  Users,
  PenTool,
  LayoutGrid,
  TestTube,
  Server,
  Cog,
} from "lucide-react";

/** Иконки для веток навыков по id ветки */
export const SKILL_BRANCH_ICONS: Record<string, LucideIcon> = {
  html_css: Code2,
  javascript: FileCode,
  typescript: Code2,
  react: Boxes,
  vue: Layers,
  svelte: Box,
  angular: Layers,
  build_tools: Package,
  a11y_perf: Gauge,
  state_routing: GitBranch,
  algorithms: Binary,
  sql: Database,
  api_design: Network,
  node: Server,
  django: Database,
  spring: Cog,
  php: Server,
  python: FileCode,
  auth_security: KeyRound,
  caching: Layers,
  manual_testing: FileCheck,
  test_design: FlaskConical,
  automation: Bug,
  ci_integration: Workflow,
  performance: BarChart3,
  documentation: FileText,
  linux_shell: Terminal,
  docker: Container,
  kubernetes: Boxes,
  cicd: Workflow,
  cloud: Cloud,
  monitoring: LineChart,
  infra_as_code: Box,
  visual_design: Palette,
  typography: Type,
  ux_research: Users,
  prototyping: PenTool,
  design_systems: LayoutGrid,
  usability: TestTube,
};
